# Generated by Django 5.2.5 on 2025-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='instructions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
